# Generated by Django 5.0.6 on 2024-06-07 04:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village_lesgrandsvoisins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailvillagelesgrandsvoisinshome",
            name="description_rich",
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name="Description Homepage"),
        ),
        migrations.AddField(
            model_name="wagtailvillagelesgrandsvoisinshome",
            name="title_rich",
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name="Titre Homepage"),
        ),
    ]
