# Generated by Django 4.2.8 on 2024-01-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_fastoche", "0010_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailfastocheconfig",
            name="search_bar",
            field=models.BooleanField(default=False, verbose_name="Barre de recherche dans l’en-tête"),
        ),
    ]
