# Generated by Django 5.0.4 on 2024-05-11 12:50

from django.db import migrations


class Migration(migrations.Migration):
    sql_query = (
        "UPDATE django_content_type SET app_label='wagtail_fastoche' WHERE app_label='content_manager';"
        "ALTER TABLE content_manager_analyticssettings RENAME TO wagtail_fastoche_analyticssettings;"
        "ALTER TABLE content_manager_cmsdsfrconfig RENAME TO wagtail_fastoche_cmsdsfrconfig;"
        "ALTER TABLE content_manager_megamenucategory RENAME TO wagtail_fastoche_megamenucategory;"
        "ALTER TABLE content_manager_megamenu RENAME TO wagtail_fastoche_megamenu;"
        "ALTER TABLE content_manager_tagcontentpage RENAME TO wagtail_fastoche_tagcontentpage;"
        "ALTER TABLE content_manager_contentpage RENAME TO wagtail_fastoche_contentpage;"
        "ALTER TABLE content_manager_socialmediaitem RENAME TO wagtail_fastoche_socialmediaitem;"
        "ALTER SEQUENCE content_manager_analyticssettings_id_seq RENAME TO wagtail_fastoche_analyticssettings_id_seq;"
        "ALTER SEQUENCE content_manager_cmsdsfrconfig_id_seq RENAME TO wagtail_fastoche_cmsdsfrconfig_id_seq;"
        "ALTER SEQUENCE content_manager_megamenu_id_seq RENAME TO wagtail_fastoche_megamenu_id_seq;"
        "ALTER SEQUENCE content_manager_megamenucategory_id_seq RENAME TO wagtail_fastoche_megamenucategory_id_seq;"
        "ALTER SEQUENCE content_manager_socialmediaitem_id_seq RENAME TO wagtail_fastoche_socialmediaitem_id_seq;"
        "ALTER SEQUENCE content_manager_tagcontentpage_id_seq RENAME TO wagtail_fastoche_tagcontentpage_id_seq;"
        "UPDATE django_migrations SET app='wagtail_fastoche' WHERE app='content_manager';"
    )

    reverse_sql_query = (
        "UPDATE django_content_type SET app_label=content_manager' WHERE app_label='wagtail_fastoche';"
        "ALTER TABLE wagtail_fastoche_analyticssettings RENAME TO content_manager_analyticssettings;"
        "ALTER TABLE wagtail_fastoche_cmsdsfrconfig RENAME TO content_manager_cmsdsfrconfig;"
        "ALTER TABLE wagtail_fastoche_megamenucategory RENAME TO content_manager_megamenucategory;"
        "ALTER TABLE wagtail_fastoche_megamenu RENAME TO content_manager_megamenu;"
        "ALTER TABLE wagtail_fastoche_tagcontentpage RENAME TO content_manager_tagcontentpage;"
        "ALTER TABLE wagtail_fastoche_contentpage RENAME TO content_manager_contentpage;"
        "ALTER TABLE wagtail_fastoche_socialmediaitem RENAME TO content_manager_socialmediaitem;"
        "ALTER SEQUENCE wagtail_fastoche_analyticssettings_id_seq RENAME TO content_manager_analyticssettings_id_seq;"
        "ALTER SEQUENCE wagtail_fastoche_cmsdsfrconfig_id_seq RENAME TO content_manager_cmsdsfrconfig_id_seq;"
        "ALTER SEQUENCE wagtail_fastoche_megamenu_id_seq RENAME TO content_manager_megamenu_id_seq;"
        "ALTER SEQUENCE wagtail_fastoche_megamenucategory_id_seq RENAME TO content_manager_megamenucategory_id_seq;"
        "ALTER SEQUENCE wagtail_fastoche_socialmediaitem_id_seq RENAME TO content_manager_socialmediaitem_id_seq;"
        "ALTER SEQUENCE wagtail_fastoche_tagcontentpage_id_seq RENAME TO content_manager_tagcontentpage_id_seq;"
        "UPDATE django_migrations SET app='content_manager' WHERE app='wagtail_fastoche';"
    )

    dependencies = [
        ("wagtail_fastoche", "0025_alter_contentpage_body"),
    ]

    operations = [
        migrations.RunSQL(sql=sql_query, reverse_sql=reverse_sql_query),
    ]
