# Generated by Django 5.0.6 on 2024-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_fastoche",
            "0027_rename_footer_description_wagtailfastocheconfig_footer_description_wagtail_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtailfastocheconfig",
            name="footer_description",
        ),
        migrations.RemoveField(
            model_name="wagtailfastocheconfig",
            name="operator_logo_file_wagtail",
        ),
    ]
