# Generated by Django 5.0.6 on 2024-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_cfran", "0027_rename_footer_description_wagtailcfranconfig_footer_description_wagtail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtailcfranconfig",
            name="footer_description",
        ),
        migrations.RemoveField(
            model_name="wagtailcfranconfig",
            name="operator_logo_file_wagtail",
        ),
    ]
