# Generated by Django 5.0.6 on 2024-06-20 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="FormPage",
        ),
    ]
