%%{init: {'theme': 'forest', "flowchart" : { "curve" : "basis" } } }%%
flowchart TD

subgraph GouvernementFR
	DSFR
end
subgraph numerique-gouv
	django-wagtailfastoche
	sites-faciles
end
subgraph Fastoche 
	web-fastoche
	django-fastoche
	wagtail-fastoche
end


django-wagtailfastoche -.-> Django 
 sites-faciles-.-> Wagtail 
 django-fastoche -.-> Django
wagtail-fastoche -.-> Wagtail 
DSFR -.-> NodeJS 
web-fastoche  -.-> NodeJS 

DSFR --> django-wagtailfastoche
django-wagtailfastoche --> sites-faciles
DSFR --> uniquement-generique{{Reprise uniquement\ndes éléments\ngénériques}}
uniquement-generique --> web-fastoche
web-fastoche --> django-fastoche

django-wagtailfastoche --> intro-submodules{{Introduction\nde submodules\npar desgin de site}}
intro-submodules --> django-fastoche
django-fastoche --> wagtail-fastoche
sites-faciles --> wagtail-fastoche

Django --> Wagtail
