%%{
  init: {
    'theme': 'base',     
    'themeVariables': {
      'primaryColor': '#bbb',
      'primaryTextColor': '#222',
      'primaryBorderColor': '#555',
      'tertiaryTextColor': '#fff',
      'lineColor': '#777',
      'secondaryColor': '#ffffffff',
      'tertiaryColor': '#555',
      'background': '#ffffff00',
      'defaultLinkColor': '#ffffffff',
      'linkColor': '#ffffffff'
    }
  }
}%%


flowchart TD


subgraph GouvernementFR["<strong><a href='https://www.info.gouv.fr' style='color:white'>GouvernementFR</a><strong>"]
  dsfr["<big><b>DSFR</big></b>
        <hr/><u>Système de design de l'Etat</u>
         <small>Outillage et gabarits de création de composants 
                prêts à l'emploi, accessibles et ergonomiques
                dans la charte graphique de l'Etat</small>"]
%%  en technologie Libre NodeJS 
%%   publié dans github principalement sous licence Libre MIT
%%   avec des mises en garde 
%%   contre l'usurpation de la marque de l'Etat
%%  </small>"]
end

subgraph numerique-gouv["<strong><a href='https://www.numerique.gouv.fr/' style='color:white'>numerique-gouv</a><strong>"]

  sites-faciles["<big><b>Sites Faciles</big></b>
             <hr/><small>Intégration Libre
                         de Django DSFR 
                         dans le gestionnaire 
                         de contenus Wagtail</small>"]
%%  Libre Wagtail publié dans github.com 
%%  sous licence Libre GNU Affero 3</small>"]

  django-dsfr["<big><b>Django DSFR</big></b>
  <hr/><small>Module public Libre
              du serveur d'applications
              Django qui intègre DSFR</small>"]
%%  publié sur pypi.org sous licence Libre.</small>"]
end

subgraph ResDigita["<strong><a href='https://www.resdigita.org/' style='color:white'>ResDigita</a><strong>"]
    wagtail-design-system["<big><b>Wagtail SitesFaciles</big></b>
                   <hr/><small>Application Libre du système 
                               de gestion de contenu Wagtail
                               qui intègre Django SitesFaciles</small>"]
    %%  dans le serveur Libre 
    %%  de gestionnaire de contenu Wagtail 
    %%  publié par github.com en Libre."]

    django-design-system["<big><b>Django SitesFaciles</big></b>
    <hr/><small>Module Libre du serveur 
                d'applications Django 
                qui intègre Génération SitesFaciles</small>"]
    %%  	dans le serveur Libre 
    %%	d'applications Django
    %%	publié par Pypi.org
    %%	et par github.com en Libre</small>"]

    design-system["<big><b>Fabrique SitesFaciles</big></b>
    <hr/><small>Génération de composants 
                HTML, CSS et Javascript
                par le système de design
                en NodeJS, SASS et EJB</small>"]
    %%	en technologie Libre NodeJS 
    %%	publié par github.com en Libre</small>"]
 end


%%  subgraph LogicielsLibres
%%      Django
%%      Wagtail
%%      NodeJS
%%  end


%%  django-dsfr <-.- Django 
%%  sites-faciles <-.- Wagtail 
%%  django-design-system <-.- Django
%%  wagtail-design-system <-.- Wagtail 
%%  design-system  <-.- NodeJS 
%%  dsfr <-.- NodeJS 


wagtail-design-system
-->
django-design-system
-->
design-system



master-design{{"<i>Système de design Libre 
                   HTML, CSS et Javascript</i>"}}:::dashedOutline
%% (dans NodeJS)</i>"}}:::dashedOutline
-.-
dsfr

master-design
-.-
design-system


master-django{{"<i>Sites et composants 
                   dynamiques Libres</i>"}}:::dashedOutline
%%  (dans Django)</i>"}}:::dashedOutline
-.-
django-dsfr 

master-django
-.-
django-design-system




master-wagtail{{"<i>Châine d'édition web Libre</i>"}}:::dashedOutline
%%  (en Wagtail)</i>"}}:::dashedOutline
-.-
sites-faciles

master-wagtail
-.-
wagtail-design-system



sites-faciles
-->
django-dsfr
-->
dsfr

master-wagtail
-->
master-django
-->
master-design


classDef dashedOutline stroke-dasharray:4 5


%%  Django --> Wagtail

click wagtail-design-system href "https://github.com/chris2fr/sites-faciles"
click django-design-system href "https://github.com/chris2fr/django-design-system"
click design-system href "https://github.com/chris2fr/design-system"
click sites-faciles href "https://github.com/numerique-gouv/sites-faciles"
click django-dsfr href "https://github.com/numerique-gouv/django-dsfr"
click dsfr href "https://github.com/GouvernementFR/dsfr/"
click ResDigita href "https://www.resdigita.org"
click numerique-gouv href "https://www.numerique.gouv.fr/"
click GouvernementFR href "https://www.info.gouv.fr/"