%%{
  init: {
    'theme': 'base',     
    'themeVariables': {
      'primaryColor': '#bbb',
      'primaryTextColor': '#222',
      'primaryBorderColor': '#555',
      'tertiaryTextColor': '#fff',
      'lineColor': '#777',
      'secondaryColor': '#eee',
      'tertiaryColor': '#555'
    }
  }
}%%


flowchart TD


subgraph GouvernementFR
  dsfr["<big><b>DSFR</big></b>
        <hr/><u>Système de design de l'Etat</u>
         <small>Outillage et gabarits de création de composants 
                prêts à l'emploi, accessibles et ergonomiques
                dans la charte graphique de l'Etat</small>"]
%%  en technologie Libre NodeJS 
%%   publié dans github principalement sous licence Libre MIT
%%   avec des mises en garde 
%%   contre l'usurpation de la marque de l'Etat
%%  </small>"]
end
subgraph numerique-gouv

  sites-faciles["<big><b>Sites Faciles</big></b>
             <hr/><small>Intégration Libre
                         de Django DSFR 
                         dans le gestionnaire 
                         de contenus Wagtail</small>"]
%%  Libre Wagtail publié dans github.com 
%%  sous licence Libre GNU Affero 3</small>"]

  django-dsfr["<big><b>Django DSFR</big></b>
  <hr/><small>Module public Libre
              du serveur d'applications
              Django qui intègre DSFR</small>"]
%%  publié sur pypi.org sous licence Libre.</small>"]
end

subgraph village.resdigita.org 
    wagtail-village["<big><b>Wagtail Village</big></b>
                   <hr/><small>Application Libre du système 
                               de gestion de contenu Wagtail
                               qui intègre Django Village</small>"]
    %%  dans le serveur Libre 
    %%  de gestionnaire de contenu Wagtail 
    %%  publié par github.com en Libre."]

    django-village["<big><b>Django Village</big></b>
    <hr/><small>Module Libre du serveur 
                d'applications Django 
                qui intègre Design Village</small>"]
    %%  	dans le serveur Libre 
    %%	d'applications Django
    %%	publié par Pypi.org
    %%	et par github.com en Libre</small>"]

    design-village["<big><b>Design Village</big></b>
    <hr/><small>Système Libre de génération
                d'interface utilisateur par NodeJS
                qui produit HTML, CSS et Javascript</small>"]
    %%	en technologie Libre NodeJS 
    %%	publié par github.com en Libre</small>"]
 end


%%  subgraph LogicielsLibres
%%      Django
%%      Wagtail
%%      NodeJS
%%  end


%%  django-dsfr <-.- Django 
%%  sites-faciles <-.- Wagtail 
%%  django-village <-.- Django
%%  wagtail-village <-.- Wagtail 
%%  design-village  <-.- NodeJS 
%%  dsfr <-.- NodeJS 


wagtail-village
-->
django-village
-->
design-village



master-design{{"<i>Charte graphique et composants webs 
                   accessibles, ergonomiques, chics
                   et personalisables Libres
                   par un système de génération 
                   HTML, CSS et Javascript en NodeJS</i>"}}:::dashedOutline
%% (dans NodeJS)</i>"}}:::dashedOutline
-.-
dsfr

master-design
-.-
design-village


master-django{{"<i>Sites et composants 
                   dynamiques Libres 
                   avec le serveur 
                   d'applications Django</i>"}}:::dashedOutline
%%  (dans Django)</i>"}}:::dashedOutline
-.-
django-dsfr 

master-django
-.-
django-village




master-wagtail{{"<i>Châine d'édition web Libre 
                    avec le système de gestion 
                    de contenus Wagtail</i>"}}:::dashedOutline
%%  (en Wagtail)</i>"}}:::dashedOutline
-.-
sites-faciles

master-wagtail
-.-
wagtail-village



sites-faciles
-->
django-dsfr
-->
dsfr

master-wagtail
-->
master-django
-->
master-design


classDef dashedOutline stroke-dasharray:4 5


%%  Django --> Wagtail

click wagtail-village href "https://github.com/chris2fr/wagtail-village"
click django-village href "https://github.com/chris2fr/django-village"
click design-village href "https://github.com/chris2fr/design-village"
click sites-faciles href "https://github.com/numerique-gouv/sites-faciles"
click django-dsfr href "https://github.com/numerique-gouv/django-dsfr"
click dsfr href "https://github.com/GouvernementFR/dsfr/"
