# Generated by Django 5.1.2 on 2024-10-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village_blog", "0004_directoryentrypage_directoryindexpage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directoryentrypage",
            options={"verbose_name": "Directory Entry", "verbose_name_plural": "Directory Entries"},
        ),
        migrations.AlterModelOptions(
            name="directoryindexpage",
            options={"verbose_name": "Directory Index"},
        ),
        migrations.AlterField(
            model_name="category",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
    ]
