# Generated by Django 5.0.6 on 2024-06-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites_faciles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagtailVillageLesgrandsvoisinsHome",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sites_faciles.contentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page Les Grands Voisins",
            },
            bases=("sites_faciles.contentpage",),
        ),
    ]
