# Generated by Django 5.0.6 on 2024-06-07 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_lesgrandsvoisins", "0003_wagtailvillagelesgrandsvoisinshome_section_2_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtailvillagelesgrandsvoisinshome",
            name="section_2_titre_rich",
        ),
    ]
