# Generated by Django 5.0.6 on 2024-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Category name"),
        ),
    ]
